rentals/urls.py
from django.urls import path
from .views import *

from django.contrib.auth.decorators import login_required

app_name = "rentals"

urlpatterns = [
    # path("", overview, name="home"),
    path("", login_required(Games.as_view()), name="games"),
    path(
        "details/<item_id>/", login_required(GameDetail.as_view()), name="game-details"
    ),
    path("platforms/", login_required(Platforms.as_view()), name="platforms"),
    path("trailers/", login_required(Trailers.as_view()), name="trailers"),
    path("orders/", rental_orders, name="rental_orders"),
    path("que/<que_id>/", mark_que_as_delivered, name="mark_que_as_delivered"),
    path("delete-game/<item_id>/", delete_rental_item, name="delete_rental_item"),
    path(
        "delete-cat/<item_id>/", delete_rental_category, name="delete_rental_category"
    ),
    path("delete_multiple_items/", delete_multiple_items, name="delete_multiple_items"),
    path(
        "delete_trailer/<trailer_id>/",
        delete_trailer,
        name="delete_trailer",
    ),
    path(
        "rental_order_details/<que_id>/",
        rental_order_details,
        name="rental_order_details",
    ),
    # rental_order_details
]

shop/urls.py
from django.urls import path
from .views import *

from django.contrib.auth.decorators import login_required

app_name = "shop"

urlpatterns = [
    path("items/", login_required(Items.as_view()), name="games"),
    path(
        "details/<item_id>/", login_required(ItemDetail.as_view()), name="item-details"
    ),
    path("platforms/", login_required(Platforms.as_view()), name="platforms"),
    path("orders/", shop_orders, name="shop_orders"),
    path("orders/<order_id>/", mark_order_as_delivered, name="mark_order_as_delivered"),
    path("delete-item/<item_id>/", delete_shop_item, name="delete_shop_item"),
    path("delete-cat/<item_id>/", delete_shop_category, name="delete_shop_category"),
    path(
        "delete_multiple_shop_items/",
        delete_multiple_shop_items,
        name="delete_multiple_shop_items",
    ),
    path(
        "shop_order_details/<order_id>/", shop_order_details, name="shop_order_details"
    ),
]

rentals/models.py
from django.db import models

# Create your models here.

rentals/views.py
from nis import cat
from django import template
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseForbidden,
    HttpResponseServerError,
)
from django.http.response import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db.models import Sum
from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage
from django.template.loader import render_to_string
from django.template import RequestContext
from django.utils.encoding import force_bytes
from requests_toolbelt.multipart.encoder import MultipartEncoder
import requests
import time
import json
from .models import *
from datetime import datetime


games_base_url = f"{settings.CLIENT_BASE_URL}rental/items/"
platform_base_url = f"{settings.CLIENT_BASE_URL}rental/platform/"
cat_base_url = f"{settings.CLIENT_BASE_URL}rental/cat/"


def overview(request):

    template = "rentals/index.html"

    context = {"page_title": "Homepage"}

    return render(request, template, context)


class Games(View):
    def get(self, request, *args, **kwargs):

        curr_date = datetime.now()

        cats = requests.get(f"{cat_base_url}?timestamp={curr_date}")

        # cats = requests.get(f"{cat_base_url}?timestamp={time.time()}")

        games = requests.get(f"{games_base_url}get_list/?timestamp={curr_date}")
        print(games.json())

        template = "rentals/games.html"

        context = {
            "page_title": "Rental Games",
            "cats": cats.json(),
            "games": games.json(),
        }

        return render(self.request, template, context)

    def post(self, request, *args, **kwargs):
        try:
            game_name = request.POST.get("game_name")
            displayImagePath = request.FILES["displayImagePath"]
            thumbnailImagePath = request.FILES["thumbnailImagePath"]
            bannerImagePath = request.FILES["bannerImagePath"]
            categoryId = request.POST.get("categoryId")
            numberInStock = request.POST.get("numberInStock")
            dailyRentalRate = request.POST.get("dailyRentalRate")
            # dailyRentalRate = request.POST.get("dailyRentalRate")
            featured = request.POST.get("featured")
            desc = request.POST.get("item_desc")

            catId = request.POST.get("categoryId")
            # for id in request.POST.getlist("categoryId"):
            #     catId.append(id)

            # catIDs = json.dumps(catId)

            # response_body = {
            #     "name": game_name,
            #     "catId": catId,
            #     "numberInStock": numberInStock,
            #     "dailyRentalRate": dailyRentalRate,
            #     "featuredinput": featured,
            # }

            # if desc:
            #     response_body.update({"desc": desc})

            multipart_data = MultipartEncoder(
                fields={
                    "displayImagePath": (
                        displayImagePath.name,
                        displayImagePath.file,
                        "image/jpeg",
                    ),
                    "thumbnailImagePath": (
                        thumbnailImagePath.name,
                        thumbnailImagePath.file,
                        "image/jpeg",
                    ),
                    "bannerImagePath": (
                        bannerImagePath.name,
                        bannerImagePath.file,
                        "image/jpeg",
                    ),
                    # plain text fields
                    "name": game_name,
                    "catId": catId,
                    "numberInStock": numberInStock,
                    "dailyRentalRate": dailyRentalRate,
                    "featured": featured,
                }
            )

            response = requests.post(
                f"{games_base_url}admin_create_item/",
                data=multipart_data,
                headers={"Content-Type": multipart_data.content_type},
            )
            if response.status_code == 200:
                print("Platform added")
                print(response.text)
                return redirect("rentals:games")
            else:
                print(response.text)
                print("Error Adding platform")
                return redirect("rentals:games")
        except Exception as e:
            print("error", e)
            return redirect("rentals:games")


class GameDetail(View):
    def get(self, request, item_id, *args, **kwargs):
        the_game = requests.get(f"{games_base_url}{item_id}")

        print(the_game.json())

        template = "rentals/rental_game_details.html"

        context = {
            "page_title": "Rental Games",
            "the_game": the_game.json(),
        }

        return render(self.request, template, context)

    def post(self, request, item_id, *args, **kwargs):

        try:

            the_item_id = request.POST.get("item_id")
            item_name = request.POST.get("item_name")
            numberInStock = request.POST.get("numberInStock")
            dailyRentalRate = request.POST.get("dailyRentalRate")
            featured = request.POST.get("featured")
            desc = request.POST.get("item_desc")

            response_files = []
            response_body = {"id": the_item_id}

            if item_name:
                response_body.update({"name": item_name})
            if numberInStock:
                response_body.update({"numberInStock": numberInStock})
            if dailyRentalRate:
                response_body.update({"dailyRentalRate": dailyRentalRate})
            if featured:
                response_body.update({"featured": featured})
            if desc:
                response_body.update({"desc": desc})

            if "displayImagePath" in request.FILES:
                response_files.append(
                    ("displayImagePath", request.FILES["displayImagePath"].file)
                )
            if "thumbnailImagePath" in request.FILES:
                response_files.append(
                    ("thumbnailImagePath", request.FILES["thumbnailImagePath"].file)
                )
            if "bannerImagePath" in request.FILES:
                response_files.append(
                    ("bannerImagePath", request.FILES["bannerImagePath"].file)
                )

            print(response_files)
            print(response_body)

            response = requests.post(
                f"{games_base_url}update_rental_game/",
                data=response_body,
                files=response_files,
            )

            if response.status_code == 200:
                print("Game Edited")
                print(response.text)
                return redirect(
                    reverse("rentals:game-details", kwargs={"item_id": item_id})
                )

            else:
                print(response.text)
                print("Error Editing Game")
                return redirect(
                    reverse("rentals:game-details", kwargs={"item_id": item_id})
                )
        except Exception as e:
            print("error", e)
            return redirect(
                reverse("rentals:game-details", kwargs={"item_id": item_id})
            )


class Platforms(View):
    def get(self, request, *args, **kwargs):
        platforms = requests.get(f"{cat_base_url}?timestamp={time.time()}")
        print(platforms.json())
        template = "rentals/platforms.html"
        context = {"page_title": "Games Categories", "platforms": platforms.json()}
        return render(self.request, template, context)

    def post(self, request, *args, **kwargs):
        platform_name = request.POST.get("platform_name")
        platform_slug = request.POST.get("platform_slug")
        iconImagePath = request.FILES["iconImagePath"]
        response_data = {"name": platform_name, "slug": platform_slug}
        response_files = {"iconImagePath": iconImagePath.file}
        multipart_data = MultipartEncoder(
            fields={
                "iconImagePath": (iconImagePath.name, iconImagePath.file, "image/jpeg"),
                "name": platform_name,
                "slug": platform_slug,
            }
        )
        response = requests.post(
            f"{cat_base_url}admin_create_cat/",
            data=multipart_data,
            headers={"Content-Type": multipart_data.content_type},
        )
        if response.status_code == 200:
            return redirect("rentals:platforms")
        else:
            return redirect("rentals:platforms")


@login_required
def rental_orders(request):
    template = "rentals/rental_orders.html"
    curr_date = datetime.now()
    que = requests.get(
        f"{settings.CLIENT_BASE_URL}rental/que/get_list/?timestamp={curr_date}"
    )
    context = {"ques": que.json()}
    return render(request, template, context)


@login_required
def rental_order_details(request, que_id):
    template = "rentals/order_details.html"
    que = requests.get(f"{settings.CLIENT_BASE_URL}rental/que/{que_id}")

    context = {"que": que.json()}
    return render(request, template, context)


@login_required
def delete_rental_item(request, item_id):
    data = {"id": item_id}
    item_del = requests.post(
        f"{games_base_url}admin_delete_item/",
        data=data,
    )
    if item_del.status_code == 200:
        print(item_del.text)
        print("Order Delivered")
        return redirect("rentals:games")
    else:
        print(item_del)
        print("There was a problem")
        return redirect("rentals:games")


@login_required
def delete_rental_category(request, item_id):
    data = {"catId": item_id}

rentals/templates/rentals/rental_orders.html
{% extends 'rentals/base.html' %}
{% load tagger %}

{% block content %}



  <!-- content @s -->
  <div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block-head nk-block-head-sm">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h3 class="nk-block-title page-title">Rental Orders</h3>
                        </div><!-- .nk-block-head-content -->
                        <div class="nk-block-head-content">
                            <div class="toggle-wrap nk-block-tools-toggle">
                                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em class="icon ni ni-more-v"></em></a>
                                <div class="toggle-expand-content" data-content="pageMenu">
                                    <ul class="nk-block-tools g-3">
                                        <li>
                                            <div class="form-control-wrap">
                                                <div class="form-icon form-icon-right">
                                                    <em class="icon ni ni-search"></em>
                                                </div>
                                                <input type="text" class="form-control" id="default-04" placeholder="Quick search by id">
                                            </div>
                                        </li>
                                    
                                
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .nk-block-head-content -->
                    </div><!-- .nk-block-between -->
                </div><!-- .nk-block-head -->
                <div class="nk-block">
                    <div class="nk-tb-list is-separate is-medium mb-3">
                        <div class="nk-tb-item nk-tb-head">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="oid">
                                    <label class="custom-control-label" for="oid"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col"><span>Order Number</span></div>
                            <div class="nk-tb-col tb-col-md"><span>Date</span></div>
                            <div class="nk-tb-col"><span class="d-none d-mb-block">Status</span></div>
                            <div class="nk-tb-col tb-col-sm"><span>Customer</span></div>
                          
                            <div class="nk-tb-col"><span>Total</span></div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1 my-n1">
                                    <li>
                                        <div class="drodown">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger mr-n1" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                
                                                    <li><a href="#"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                          
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-tb-item -->


                        {% if ques %}
                        {% for val in ques %}
                        <div class="nk-tb-item">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="oid01">
                                    <label class="custom-control-label" for="oid01"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col">
                                <span class="tb-lead"><a href="#">#{{val.ref_code}}</a></span>
                            </div>
                            <div class="nk-tb-col tb-col-md">
                                <span class="tb-sub">{{val.ordered_date}}</span>
                            </div>
                            <div class="nk-tb-col">
                                {% if val.received == False %}
                                <span class="dot bg-warning d-mb-none"></span>
                                <span class="badge badge-sm badge-dot has-bg badge-warning d-none d-mb-inline-flex">In Transit</span>
                                {% elif val.received == True %}
                                <span class="dot bg-success d-mb-none"></span>
                                <span class="badge badge-sm badge-dot has-bg badge-success d-none d-mb-inline-flex">Delivered</span>
                                {% endif %}
                            </div>
                            <div class="nk-tb-col tb-col-sm">
                                <span class="tb-sub">{{val.user.first_name}} {{val.user.last_name}} </span>
                            </div>
                            
                            <div class="nk-tb-col">
                                <span class="tb-lead">₦ {{val.que_total}}</span>
                            </div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1">
                                    <li class="nk-tb-action-hidden"><a href="{% url 'rentals:mark_que_as_delivered' val.id %}" class="btn btn-icon btn-trigger btn-tooltip" title="Mark as Delivered" >
                                            <em class="icon ni ni-truck"></em></a></li>
                                    <li class="nk-tb-action-hidden"><a href="{% url 'rentals:rental_order_details' val.id %}" class="btn btn-icon btn-trigger btn-tooltip" title="View Order">
                                            <em class="icon ni ni-eye"></em></a></li>
                                    <li>
                                        <div class="drodown mr-n1">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                    <li><a href="{% url 'rentals:rental_order_details' val.id %}"><em class="icon ni ni-eye"></em><span>Order Details</span></a></li>
                                                    <li><a href="{% url 'rentals:mark_que_as_delivered' val.id %}"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                 
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}







                    </div><!-- .nk-tb-list -->
                    
                </div><!-- .nk-block -->
            </div>
        </div>
    </div>
</div>
<!-- content @e -->

{% endblock content %}

rentals/templates/rentals/trailers.html
{% extends 'rentals/base.html' %}
{% load tagger %}

{% block content %}


                <!-- content @s -->
                <div class="nk-content ">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="nk-block-head nk-block-head-sm">
                                    <div class="nk-block-between g-3">
                                        <div class="nk-block-head-content">
                                            <h3 class="nk-block-title page-title">Game Trailers</h3>
                                            <div class="nk-block-des text-soft">
                                                <p>You have total <span class="text-base"> {{count}} </span> Trailers.</p>
                                            </div>
                                        </div>
                                        <div class="nk-block-head-content">
                                            <a href="#" data-target="addProduct" class="toggle btn btn-outline-light bg-white d-none d-sm-inline-flex"><em class="icon ni ni-plus"></em><span>Add new Trailer</span></a>
                                            <a href="#" data-target="addProduct" class="toggle btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em class="icon ni ni-download-cloud"></em></a>
                                        </div>
                                    </div>
                                </div><!-- .nk-block-head -->



                                <div class="nk-block">
                                    <div class="row g-gs">

                                        {% if trailers %}
                                        {% for val in trailers %}
                                        <div class="col-sm-6 col-lg-4 col-xxl-3">
                                            <div class="gallery card card-bordered">
                                                <a class="gallery-image popup-image" href="{{val.trailer_banner}}">
                                                    <img class="w-100 rounded-top" src="{{val.trailer_banner}}"  alt="">
                                                </a>
                                                <div class="gallery-body card-inner align-center justify-between flex-wrap g-2">
                                                    <div class="user-card">
                                                      
                                                        <div class="user-info">
                                                            <span class="lead-text">{{val.highlight_title}}</span>
                                              
                                                        </div>
                                                    </div>

                                                    <div>
                                                        <a href="{% url 'rentals:delete_trailer' val.id %}" class="btn btn-p-0 btn-nofocus"><em class="icon ni ni-trash"></em></a>
                                                    </div>
                                                   
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        {% endif %}
                                        
                                        

                                    </div>
                                </div>





                                <div class="nk-add-product toggle-slide toggle-slide-right" data-content="addProduct" data-toggle-screen="any" data-toggle-overlay="true" data-toggle-body="true" data-simplebar>
                                    <div class="nk-block-head">
                                        <div class="nk-block-head-content">
                                            <h5 class="nk-block-title">Add New Trailer</h5>
                                            <div class="nk-block-des">
                                                <p>Add information and add new trailer.</p>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <form action="#" method="post" enctype="multipart/form-data" >
                                        {% csrf_token %}
                                    <div class="nk-block">
                                        <div class="row g-3">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="name">Game Name </label>
                                                    <div class="form-control-wrap">
                                                        <input name="name" type="text" class="form-control" id="name" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="title">Trailer Title </label>
                                                    <div class="form-control-wrap">
                                                        <input name="title" type="text" class="form-control" id="title" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="trailerBanner"> Trailer Banner  </label>
                                                    <div class="form-control-wrap">
                                                        <div class="custom-file">
                                                            <input name="trailerBanner" type="file" class="custom-file-input" id="trailerBanner" required> 
                                                            <label class="custom-file-label" for="trailerBanner">Choose file</label> 
                                                        </div>
                                                    </div>
                                                </div>
                                            
                                            </div>

                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="desc">Trailer Short Description </label>
                                                    <div class="form-control-wrap">
                                                        <input name="desc" type="text" class="form-control" id="desc">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="yt_url">Trailer Youtube URL</label>
                                                    <div class="form-control-wrap">
                                                        <input name="yt_url" type="text" class="form-control" id="yt_url" required>
                                                    </div>
                                                </div>
                                            </div>
                                           

         
                                           
                                          
                                        
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary"><em class="icon ni ni-plus"></em><span>Add New</span></button>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block -->
                                </form>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
                <!-- content @e -->


{% endblock content %}