shop/urls.py
from django.urls import path
from .views import *

from django.contrib.auth.decorators import login_required

app_name = "shop"

urlpatterns = [
    path("items/", login_required(Items.as_view()), name="games"),
    path(
        "details/<item_id>/", login_required(ItemDetail.as_view()), name="item-details"
    ),
    path("platforms/", login_required(Platforms.as_view()), name="platforms"),
    path("orders/", shop_orders, name="shop_orders"),
    path("orders/<order_id>/", mark_order_as_delivered, name="mark_order_as_delivered"),
    path("delete-item/<item_id>/", delete_shop_item, name="delete_shop_item"),
    path("delete-cat/<item_id>/", delete_shop_category, name="delete_shop_category"),
    path(
        "delete_multiple_shop_items/",
        delete_multiple_shop_items,
        name="delete_multiple_shop_items",
    ),
    path(
        "shop_order_details/<order_id>/", shop_order_details, name="shop_order_details"
    ),
]

vendors/urls.py
from django.urls import path
from .views import *

app_name = "vendors"

urlpatterns = [
    path("all-vendors/", all_vendors, name="all-vendors"),
    path("approve_kyc/<kyc_id>/", approve_kyc, name="approve_kyc"),
    path("get_user_details/<user_email>/", get_vendor_details, name="get_user_details"),
    path("vendor-items/", Items.as_view(), name="vendor-items"),
    path("details/<item_id>/", ItemDetail.as_view(), name="item-details"),
    path("rental-vendor-items/", RentalGame.as_view(), name="rental-vendor-items"),
    path(
        "rental-details/<item_id>/",
        RentalGameDetail.as_view(),
        name="rental-item-details",
    ),
    path("approve-item/<item_id>/", approve_item, name="approve-item"),
    path("reject-item/<item_id>/", reject_item, name="reject-item"),
    path(
        "approve-rental-item/<item_id>/",
        approve_rental_item,
        name="approve-rental-item",
    ),
    path(
        "reject-rental-item/<item_id>/", reject_rental_item, name="reject-rental-item"
    ),
]

vendors/models.py
from django.db import models

# Create your models here.

vendors/views.py
from multiprocessing import context
from django import template
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseForbidden,
    HttpResponseServerError,
)
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db.models import Sum
from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage
from django.template.loader import render_to_string
from django.template import RequestContext
from django.utils.encoding import force_bytes
from requests_toolbelt.multipart.encoder import MultipartEncoder
import requests
import time
import json
from .models import *
from datetime import datetime


vendor_base_url = f"{settings.VENDOR_BASE_URL}api/v1/vendors"

ts = time.time()


def all_vendors(request):

    template = "vendors/all_vendors.html"

    all_vendors = requests.get(f"{vendor_base_url}/get_all_users/?timestamp={ts}")

    print(all_vendors.json())

    context = {"all_vendors": all_vendors.json()}

    return render(request, template, context)


def get_vendor_details(request, user_email):

    template = "vendors/vendor_details.html"

    the_res = requests.post(
        f"{vendor_base_url}/get_user_details/", data={"email": user_email}
    )
    print(the_res.json())

    context = {"user": the_res.json()}

    return render(request, template, context)


def approve_kyc(request, kyc_id):
    the_res = requests.post(f"{vendor_base_url}/approve_kyc/", data={"kyc_id": kyc_id})
    print(the_res.json())
    if the_res.status_code == 200:
        print("KYC approved")
    return redirect("vendors:all-vendors")


class Items(View):
    def get(self, request, *args, **kwargs):
        curr_date = datetime.now()

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/shop/items/"

        items = requests.get(f"{items_base_url}get_list/?timestamp={curr_date}")
        print(items.json())

        template = "vendors/vendor_items.html"

        context = {
            "page_title": "Approve Vendor Items",
            "items": items.json(),
        }

        return render(self.request, template, context)


class ItemDetail(View):
    def get(self, request, item_id, *args, **kwargs):

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/shop/items/"
        the_item = requests.get(f"{items_base_url}{item_id}")

        print(the_item.json())

        template = "vendors/vendor_item_details.html"

        context = {
            "page_title": "Vendor Item Details",
            "the_game": the_item.json(),
        }

        return render(self.request, template, context)


# @login_required
def approve_item(request, item_id):

    try:
        # first get the item
        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/shop/items/"
        the_item = requests.get(f"{items_base_url}{item_id}").json()
        print("the_item", the_item)
        # create new item to client end
        client_items_base_url = f"{settings.CLIENT_BASE_URL}shop/items/"
        # admin_vendor_create_item
        sendBody = {
            "name": the_item["name"],
            "catName": the_item["cat"],
            "numberInStock": the_item["numberInStock"],
            "price": the_item["price"],
            "vendor_code": the_item["vendor"]["vendor_code"],
            # "vendor_long": the_item["vendor"]["addressObject"]["long"],
            # "vendor_lat": the_item["vendor"]["addressObject"]["lat"],
            "displayImagePath": the_item["displayImagePath"],
            "bannerImagePath": the_item["bannerImagePath"],
            "thumbnailImagePath": the_item["thumbnailImagePath"],
        }
        if the_item["discount_price"]:
            sendBody.update({"discount_price": the_item["discount_price"]})

        if the_item["desc"]:
            sendBody.update({"desc": the_item["desc"]})

        if (
            the_item["vendor"]["addressObject"]["long"]
            and the_item["vendor"]["addressObject"]["long"] != None
        ):
            sendBody.update(
                {"vendor_long": the_item["vendor"]["addressObject"]["long"]}
            )

        if (
            the_item["vendor"]["addressObject"]["lat"]
            and the_item["vendor"]["addressObject"]["lat"] != None
        ):
            sendBody.update({"vendor_lat": the_item["vendor"]["addressObject"]["lat"]})

        if the_item["vendor"]["shop_name"] == None:
            sendBody.update(
                {
                    "vendor": f"{the_item['vendor']['first_name']}{the_item['vendor']['last_name']}"
                }
            )
        else:
            sendBody.update({"vendor": the_item["vendor"]["shop_name"]})

        print(sendBody)

        sendResponse = requests.post(
            f"{client_items_base_url}admin_vendor_create_item/",
            data=sendBody,
        )
        if sendResponse.status_code == 200:
            approval_data = {"id": item_id}
            item_approval = requests.post(
                f"{items_base_url}approve_item/",
                data=approval_data,
            )
            print(item_approval)
            return redirect("vendors:vendor-items")
        else:
            print("there was a problem")
            return redirect("vendors:vendor-items")

    except Exception as e:
        print(e)
        return redirect("vendors:vendor-items")


# @login_required
def reject_item(request, item_id):
    try:
        reject_data = {"id": item_id}

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/shop/items/"
        item_rejection = requests.post(
            f"{items_base_url}reject_item/",
            data=reject_data,
        )
        if item_rejection.status_code == 200:
            print("item removed")
            return redirect("vendors:vendor-items")
        else:
            print("there was a problem")
            return redirect("vendors:vendor-items")

    except Exception as e:
        print(e)
        return redirect("vendors:vendor-items")


class RentalGame(View):
    def get(self, request, *args, **kwargs):

        curr_date = datetime.now()

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/rental/items/"

        items = requests.get(f"{items_base_url}get_list/?timestamp={curr_date}")

        template = "vendors/rental_vendor_items.html"

        context = {
            "page_title": "Approve Vendor Rental Games",
            "items": items.json(),
        }

        return render(self.request, template, context)


class RentalGameDetail(View):
    def get(self, request, item_id, *args, **kwargs):

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/rental/items/"
        the_item = requests.get(f"{items_base_url}{item_id}")

        # print(the_item.json())

        template = "vendors/rental_vendor_item_details.html"

        context = {
            "page_title": "Vendor Rental Item Details",
            "the_game": the_item.json(),
        }

        return render(self.request, template, context)


# @login_required
def approve_rental_item(request, item_id):

    try:
        # first get the item
        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/rental/items/"
        the_item = requests.get(f"{items_base_url}{item_id}").json()
        # print("the_item", the_item)
        # create new item to client end
        client_items_base_url = f"{settings.CLIENT_BASE_URL}rental/items/"
        # admin_vendor_create_item
        sendBody = {
            "name": the_item["name"],
            "catName": the_item["cat"],
            "numberInStock": the_item["numberInStock"],
            "dailyRentalRate": the_item["dailyRentalRate"],
            "vendor_code": the_item["vendor"]["vendor_code"],
            "displayImagePath": the_item["displayImagePath"],
            "bannerImagePath": the_item["bannerImagePath"],
            "thumbnailImagePath": the_item["thumbnailImagePath"],
        }

        if the_item["desc"]:
            sendBody.update({"desc": the_item["desc"]})

        if the_item["vendor"]["shop_name"] == None:
            sendBody.update(
                {
                    "vendor": f"{the_item['vendor']['first_name']}{the_item['vendor']['last_name']}"
                }
            )
        else:
            sendBody.update({"vendor": the_item["vendor"]["shop_name"]})

        if (
            the_item["vendor"]["addressObject"]["long"]
            and the_item["vendor"]["addressObject"]["long"] != None
        ):
            sendBody.update(
                {"vendor_long": the_item["vendor"]["addressObject"]["long"]}
            )

        if (
            the_item["vendor"]["addressObject"]["lat"]
            and the_item["vendor"]["addressObject"]["lat"] != None
        ):
            sendBody.update({"vendor_lat": the_item["vendor"]["addressObject"]["lat"]})

        print("sendbody here ", sendBody)

        sendResponse = requests.post(
            f"{client_items_base_url}admin_vendor_create_item/",
            data=sendBody,
        )
        if sendResponse.status_code == 200:
            approval_data = {"id": item_id}
            item_approval = requests.post(
                f"{items_base_url}approve_item/",
                data=approval_data,
            )
            print(item_approval)
            return redirect("vendors:rental-vendor-items")
        else:
            print("there was a problem")
            return redirect("vendors:rental-vendor-items")

    except Exception as e:
        print(e)
        return redirect("vendors:rental-vendor-items")


# @login_required
def reject_rental_item(request, item_id):
    try:
        reject_data = {"id": item_id}

        items_base_url = f"{settings.VENDOR_BASE_URL}api/v1/rental/items/"

vendors/templates/vendors/rental_vendor_item_details.html
{% extends 'rentals/base.html' %}
{% load tagger %}
{% load humanize %}

{% block content %}


    <!-- content @s -->
    <div class="nk-content ">
        <div class="container">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between g-3">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">Rental Item Details</h3>
                                <div class="nk-block-des text-soft">
                                   
                                </div>
                            </div>
                            <div class="nk-block-head-content">
                                <a href="{% url 'vendors:rental-vendor-items' %}" class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em class="icon ni ni-arrow-left"></em><span>Back</span></a>
                                <a href="{% url 'vendors:rental-vendor-items' %}" class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em class="icon ni ni-arrow-left"></em></a>
                            </div>
                        </div>
                    </div><!-- .nk-block-head -->
                    <div class="nk-block">
                        <div class="card card-bordered">
                            <div class="card-inner">
                                <div class="row pb-5">
                                    <div class="col-lg-6">
                                        <div class="product-gallery mr-xl-1 mr-xxl-5">
                                            <div class="slider-init" id="sliderFor" data-slick='{"arrows": false, "fade": true, "asNavFor":"#sliderNav", "slidesToShow": 1, "slidesToScroll": 1}'>
                                                <div class="slider-item rounded">
                                                    <img src="{{the_game.thumbnailImagePath}}" class="rounded w-100" alt="">
                                                </div>

                                            </div>
                                        
                                        </div>
                                    </div><!-- .col -->
                                    <div class="col-lg-6">
                                        <div class="product-info mt-5 mr-xxl-5">
                                            <h4 class="product-price text-primary">N{{the_game.dailyRentalRate}} </h4>
                                            <h2 class="product-title">{{the_game.name}}</h2>
                                           
                                            <div class="product-excrept text-soft">
                                                <p class="lead"> {{the_game.desc}} </p>
                                            </div>
                                            <div class="product-meta">
                                                <ul class="d-flex g-3 gx-5">
                                                    <li>
                                                        <div class="fs-14px text-muted">Vendor</div>
                                                        <div class="fs-16px fw-bold text-secondary"> {{the_game.vendor.first_name}} {{the_game.vendor.last_name}} </div>
                                                    </li>
                                                    <li>
                                                        <div class="fs-14px text-muted">Platform</div>
                                                        <div class="fs-16px fw-bold text-secondary">{{the_game.cat}}</div>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="product-meta">
                                                <h6 class="title">Date Added</h6>
                                                <p class="lead"> {{the_game.created_at|naturaltime}} </p>
                                                
                                            </div>

                                          
                                        </div><!-- .product-info -->
                                    </div><!-- .col -->
                                </div><!-- .row -->
                                <hr class="hr border-light">
                                <div class="row g-gs flex-lg-row-reverse pt-5">

                                    

                                        <div class="card col-md-6">
                                            <div class="card-inner">
                                                <div class="card-head">
                                                    <h5 class="card-title"> Banner </h5>
                                                </div>
                                                <div class="card-body">
                                                    <img src="{{the_game.bannerImagePath}}" alt="">
                                                </div>
                                                
                                            </div>
                                        </div> 
                                        

                                        <div class="card col-md-6">
                                            <div class="card-inner">
                                                <div class="card-head">
                                                    <h5 class="card-title"> Display Image </h5>
                                                </div>
                                                <div class="card-body">
                                                    <img src="{{the_game.displayImagePath}}" alt="">
                                                </div>
                                                
                                            </div>
                                        </div>
                                        {% if the_game.admin_approved == False %}
                                        <div class="col-md-6">
                                          
                                                <a  href="{% url 'vendors:approve-rental-item' the_game.id %}" style="color: white !important ;" class="btn btn-lg btn-primary">Approve Item</a>
                                        
                                        </div>
                                        

                                        <div class="col-md-6">
    
                                            <a href="{% url 'vendors:reject-rental-item' the_game.id %}" style="color: white !important ;"  class="btn btn-lg btn-danger">Reject Item</a>
                                    
                                    </div>
                                    {% else %}

                                    <div class="col-md-6">
    
                                        <a href="{% url 'vendors:reject-rental-item' the_game.id %}" style="color: white !important ;"  class="btn btn-lg btn-danger">Remove Item</a>
                                
                                     </div>

                                    {% endif %}
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div><!-- .nk-block -->




                </div>
            </div>
        </div>
    </div>
    <!-- content @e -->


{% endblock content %}

vendors/templates/vendors/vendor_item_details.html
{% extends 'rentals/base.html' %}
{% load tagger %}
{% load humanize %}

{% block content %}


    <!-- content @s -->
    <div class="nk-content ">
        <div class="container">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between g-3">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">Sale Item Details</h3>
                                <div class="nk-block-des text-soft">
                                   
                                </div>
                            </div>
                            <div class="nk-block-head-content">
                                <a href="{% url 'vendors:vendor-items' %}" class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em class="icon ni ni-arrow-left"></em><span>Back</span></a>
                                <a href="{% url 'vendors:vendor-items' %}" class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em class="icon ni ni-arrow-left"></em></a>
                            </div>
                        </div>
                    </div><!-- .nk-block-head -->
                    <div class="nk-block">
                        <div class="card card-bordered">
                            <div class="card-inner">
                                <div class="row pb-5">
                                    <div class="col-lg-6">
                                        <div class="product-gallery mr-xl-1 mr-xxl-5">
                                            <div class="slider-init" id="sliderFor" data-slick='{"arrows": false, "fade": true, "asNavFor":"#sliderNav", "slidesToShow": 1, "slidesToScroll": 1}'>
                                                <div class="slider-item rounded">
                                                    <img src="{{the_game.thumbnailImagePath}}" class="rounded w-100" alt="">
                                                </div>

                                            </div>
                                        
                                        </div>
                                    </div><!-- .col -->
                                    <div class="col-lg-6">
                                        <div class="product-info mt-5 mr-xxl-5">
                                            <h4 class="product-price text-primary">N{{the_game.price}} </h4>
                                            <h2 class="product-title">{{the_game.name}}</h2>
                                           
                                            <div class="product-excrept text-soft">
                                                <p class="lead"> {{the_game.desc}} </p>
                                            </div>
                                            <div class="product-meta">
                                                <ul class="d-flex g-3 gx-5">
                                                    <li>
                                                        <div class="fs-14px text-muted">Vendor</div>
                                                        <div class="fs-16px fw-bold text-secondary"> {{the_game.vendor.first_name}} {{the_game.vendor.last_name}} </div>
                                                    </li>
                                                    <li>
                                                        <div class="fs-14px text-muted">Platform</div>
                                                        <div class="fs-16px fw-bold text-secondary">{{the_game.cat}}</div>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="product-meta">
                                                <h6 class="title">Date Added</h6>
                                                <p class="lead"> {{the_game.created_at|naturaltime}} </p>
                                                
                                            </div>

                                          
                                        </div><!-- .product-info -->
                                    </div><!-- .col -->
                                </div><!-- .row -->
                                <hr class="hr border-light">
                                <div class="row g-gs flex-lg-row-reverse pt-5">

                                    

                                        <div class="card col-md-6">
                                            <div class="card-inner">
                                                <div class="card-head">
                                                    <h5 class="card-title"> Banner </h5>
                                                </div>
                                                <div class="card-body">
                                                    <img src="{{the_game.bannerImagePath}}" alt="">
                                                </div>
                                                
                                            </div>
                                        </div> 
                                        

                                        <div class="card col-md-6">
                                            <div class="card-inner">
                                                <div class="card-head">
                                                    <h5 class="card-title"> Display Image </h5>
                                                </div>
                                                <div class="card-body">
                                                    <img src="{{the_game.displayImagePath}}" alt="">
                                                </div>
                                                
                                            </div>
                                        </div>
                                        {% if the_game.admin_approved == False %}
                                        <div class="col-md-6">
                                          
                                                <a  href="{% url 'vendors:approve-item' the_game.id %}" style="color: white !important ;" class="btn btn-lg btn-primary">Approve Item</a>
                                        
                                        </div>
                                        

                                        <div class="col-md-6">
    
                                            <a href="{% url 'vendors:reject-item' the_game.id %}" style="color: white !important ;"  class="btn btn-lg btn-danger">Reject Item</a>
                                    
                                    </div>
                                    {% else %}

                                    <div class="col-md-6">
    
                                        <a href="{% url 'vendors:reject-item' the_game.id %}" style="color: white !important ;"  class="btn btn-lg btn-danger">Remove Item</a>
                                
                                     </div>

                                    {% endif %}
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div><!-- .nk-block -->




                </div>
            </div>
        </div>
    </div>
    <!-- content @e -->


{% endblock content %}