shop/urls.py
from django.urls import path
from .views import *

from django.contrib.auth.decorators import login_required

app_name = "shop"

urlpatterns = [
    path("items/", login_required(Items.as_view()), name="games"),
    path(
        "details/<item_id>/", login_required(ItemDetail.as_view()), name="item-details"
    ),
    path("platforms/", login_required(Platforms.as_view()), name="platforms"),
    path("orders/", shop_orders, name="shop_orders"),
    path("orders/<order_id>/", mark_order_as_delivered, name="mark_order_as_delivered"),
    path("delete-item/<item_id>/", delete_shop_item, name="delete_shop_item"),
    path("delete-cat/<item_id>/", delete_shop_category, name="delete_shop_category"),
    path(
        "delete_multiple_shop_items/",
        delete_multiple_shop_items,
        name="delete_multiple_shop_items",
    ),
    path(
        "shop_order_details/<order_id>/", shop_order_details, name="shop_order_details"
    ),
]

shop/models.py
from django.db import models

# Create your models here.

shop/views.py
from datetime import datetime
from django import template
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseForbidden,
    HttpResponseServerError,
)
from django.http.response import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db.models import Sum
from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage
from django.template.loader import render_to_string
from django.template import RequestContext
from django.utils.encoding import force_bytes
from requests_toolbelt.multipart.encoder import MultipartEncoder
import time
import requests
import json
from .models import *


items_base_url = f"{settings.CLIENT_BASE_URL}shop/items/"
platform_base_url = f"{settings.CLIENT_BASE_URL}shop/item/platform/"
cat_base_url = f"{settings.CLIENT_BASE_URL}shop/item/cat/"


class Items(View):
    def get(self, request, *args, **kwargs):

        # platforms = requests.get(f"{platform_base_url}?timestamp={time.time()}")

        curr_date = datetime.now()

        cats = requests.get(f"{cat_base_url}?timestamp={curr_date}")

        items = requests.get(f"{items_base_url}get_list?timestamp={curr_date}")
        for val in items.json():
            print(val["name"])

        template = "shop/games.html"

        context = {
            "page_title": "Shop Items",
            # "platforms": platforms.json(),
            "cats": cats.json(),
            "games": items.json(),
        }

        return render(self.request, template, context)

    def post(self, request, *args, **kwargs):
        try:
            game_name = request.POST.get("game_name")
            displayImagePath = request.FILES["displayImagePath"]
            thumbnailImagePath = request.FILES["thumbnailImagePath"]
            bannerImagePath = request.FILES["bannerImagePath"]
            # platformId = request.POST.get("platformId")
            numberInStock = request.POST.get("numberInStock")
            price = request.POST.get("price")
            discount_price = request.POST.get("discount_price")
            featured = request.POST.get("featured")
            desc = request.POST.get("item_desc")

            catId = request.POST.get("categoryId")
            # for id in request.POST.getlist("categoryId"):
            #     catId.append(id)

            # catIDs = json.dumps(catId)

            # response_body = {
            #     "name": game_name,
            #     "catId": catId,
            #     "numberInStock": numberInStock,
            #     "price": price,
            #     "featuredinput": featured,
            # }
            # if discount_price:
            #     response_body.update({"discount_price": discount_price})

            # if desc:
            #     response_body.update({"desc": desc})

            multipart_data = MultipartEncoder(
                fields={
                    "displayImagePath": (
                        displayImagePath.name,
                        displayImagePath.file,
                        "image/jpeg",
                    ),
                    "thumbnailImagePath": (
                        thumbnailImagePath.name,
                        thumbnailImagePath.file,
                        "image/jpeg",
                    ),
                    "bannerImagePath": (
                        bannerImagePath.name,
                        bannerImagePath.file,
                        "image/jpeg",
                    ),
                    "name": game_name,
                    "catId": catId,
                    "numberInStock": numberInStock,
                    "price": price,
                    "featured": featured,
                    "desc": desc,
                }
            )
            print(multipart_data)

            response = requests.post(
                f"{items_base_url}admin_create_item/",
                data=multipart_data,
                headers={"Content-Type": multipart_data.content_type},
            )

            if response.status_code == 200:
                return redirect("shop:games")
            else:
                return redirect("shop:games")
        except Exception as e:
            print("error is", e)
            return redirect("shop:games")


class ItemDetail(View):
    def get(self, request, item_id, *args, **kwargs):
        the_item = requests.get(f"{items_base_url}{item_id}")

        print(the_item.json())

        template = "shop/sale_items_details.html"

        context = {
            "page_title": "Shop Items",
            "the_game": the_item.json(),
        }

        return render(self.request, template, context)

    def post(self, request, item_id, *args, **kwargs):
        try:

            the_item_id = request.POST.get("item_id")
            item_name = request.POST.get("item_name")
            numberInStock = request.POST.get("numberInStock")
            price = request.POST.get("price")
            discount_price = request.POST.get("discount_price")
            featured = request.POST.get("featured")
            desc = request.POST.get("item_desc")

            response_files = []
            response_body = {"id": the_item_id}

            if item_name:
                response_body.update({"name": item_name})
            if numberInStock:
                response_body.update({"numberInStock": numberInStock})
            if price:
                response_body.update({"price": price})

            if discount_price:
                response_body.update({"discount_price": discount_price})
            if featured:
                response_body.update({"featured": featured})

            if desc:
                response_body.update({"desc": desc})

            if "displayImagePath" in request.FILES:
                response_files.append(
                    ("displayImagePath", request.FILES["displayImagePath"].file)
                )
            if "thumbnailImagePath" in request.FILES:
                response_files.append(
                    ("thumbnailImagePath", request.FILES["thumbnailImagePath"].file)
                )
            if "bannerImagePath" in request.FILES:
                response_files.append(
                    ("bannerImagePath", request.FILES["bannerImagePath"].file)
                )

            print(response_files)
            print(response_body)

            response = requests.post(
                f"{items_base_url}update_shop_item/",
                data=response_body,
                files=response_files,
            )

            if response.status_code == 200:
                print("Item Edited")
                print(response.text)
                return redirect(
                    reverse("shop:item-details", kwargs={"item_id": item_id})
                )

            else:
                print(response.text)
                print("Error Editing Game")
                return redirect(
                    reverse("shop:item-details", kwargs={"item_id": item_id})
                )
        except Exception as e:
            print("error", e)
            return redirect(reverse("shop:item-details", kwargs={"item_id": item_id}))


class Platforms(View):
    def get(self, request, *args, **kwargs):
        platforms = requests.get(f"{cat_base_url}?timestamp={time.time()}")
        template = "shop/platforms.html"
        context = {"page_title": "Games Categories", "platforms": platforms.json()}
        return render(self.request, template, context)

    def post(self, request, *args, **kwargs):
        platform_name = request.POST.get("platform_name")
        platform_slug = request.POST.get("platform_slug")
        iconImagePath = request.FILES["iconImagePath"]
        response_data = {"name": platform_name, "slug": platform_slug}
        response_files = {"iconImagePath": iconImagePath.file}
        multipart_data = MultipartEncoder(
            fields={
                "iconImagePath": (iconImagePath.name, iconImagePath.file, "image/jpeg"),
                "name": platform_name,
                "slug": platform_slug,
            }
        )
        # response = requests.post(f"{platform_base_url}", json=response_data)
        response = requests.post(
            f"{cat_base_url}admin_create_cat/",
            data=multipart_data,
            headers={"Content-Type": multipart_data.content_type},
        )
        if response.status_code == 200:
            return redirect("shop:platforms")
        else:
            return redirect("shop:platforms")


@login_required
def shop_orders(request):
    template = "shop/shop_orders.html"
    curr_date = datetime.now()
    orders = requests.get(
        f"{settings.CLIENT_BASE_URL}shop/item/order/get_list/?timestamp={curr_date}"
    )
    context = {"orders": orders.json()}
    return render(request, template, context)


@login_required
def shop_order_details(request, order_id):
    template = "shop/shop_order_details.html"
    order = requests.get(f"{settings.CLIENT_BASE_URL}shop/item/order/{order_id}")
    context = {"order": order.json()}
    return render(request, template, context)


@login_required
def mark_order_as_delivered(request, order_id):
    data = {"id": order_id}
    order_del = requests.post(
        f"{settings.CLIENT_BASE_URL}shop/item/order/mark_as_delivered/", data=data
    )
    if order_del.status_code == 200:
        return redirect("shop:shop_orders")
    else:
        return redirect("shop:shop_orders")


@login_required
def delete_shop_item(request, item_id):
    data = {"id": item_id}
    item_del = response = requests.post(
        f"{items_base_url}admin_delete_item/",
        data=data,
    )
    if item_del.status_code == 200:

shop/templates/shop/platforms.html
{% extends 'rentals/base.html' %}

{% block content %}


                <!-- content @s -->
                <div class="nk-content ">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="nk-block-head nk-block-head-sm">
                                    <div class="nk-block-between">
                                        <div class="nk-block-head-content">
                                            <h3 class="nk-block-title page-title">Categories</h3>
                                        </div><!-- .nk-block-head-content -->
                                        <div class="nk-block-head-content">
                                            <div class="toggle-wrap nk-block-tools-toggle">
                                                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em class="icon ni ni-more-v"></em></a>
                                                <div class="toggle-expand-content" data-content="pageMenu">
                                                    <ul class="nk-block-tools g-3">
                                                        <li>
                                                            <div class="form-control-wrap">
                                                                <div class="form-icon form-icon-right">
                                                                    <em class="icon ni ni-search"></em>
                                                                </div>
                                                                <input type="text" class="form-control" id="default-04" placeholder="Quick search by id">
                                                            </div>
                                                        </li>
                                                        
                                                        <li class="nk-block-tools-opt">
                                                            <a href="#" data-target="addProduct" class="toggle btn btn-icon btn-primary d-md-none"><em class="icon ni ni-plus"></em></a>
                                                            <a href="#" data-target="addProduct" class="toggle btn btn-primary d-none d-md-inline-flex"><em class="icon ni ni-plus"></em><span>Add New Category</span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div><!-- .nk-block-head-content -->
                                    </div><!-- .nk-block-between -->
                                </div><!-- .nk-block-head -->
                                <div class="nk-block">
                                    <div class="nk-tb-list is-separate mb-3">
                                        <div class="nk-tb-item nk-tb-head">
                                           
                                            <div class="nk-tb-col tb-col-sm"><span>Category Name</span></div>
                                            <div class="nk-tb-col"><span>Slug</span></div>
                                         
                                            <div class="nk-tb-col tb-col-md"><em class="tb-asterisk icon ni ni-star-round"></em></div>
                                            <div class="nk-tb-col nk-tb-col-tools">
                                                <ul class="nk-tb-actions gx-1 my-n1">
                                                    <li class="mr-n1">
                                                        <div class="dropdown">
                                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                <ul class="link-list-opt no-bdr">
                                                                    <li><a href="#"><em class="icon ni ni-edit"></em><span>Delete Category</span></a></li>
                                                             
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div><!-- .nk-tb-item -->


                                        {% if platforms %}
                                        {% for os in platforms %}
                                        <div class="nk-tb-item">
                                            
                                            <div class="nk-tb-col tb-col-sm">
                                                <span class="tb-product">
                                                    <img src="{{os.iconImagePath}}" alt="" class="thumb">
                                                    <span class="title">{{os.name}}</span>
                                                </span>
                                            </div>
                                            <div class="nk-tb-col">
                                                <span class="tb-sub">{{os.slug}}</span>
                                            </div>
                                       
                                           
                                         
                                            <div class="nk-tb-col tb-col-md">
                                                <div class="asterisk tb-asterisk">
                                                    <a href="#"><em class="asterisk-off icon ni ni-star"></em><em class="asterisk-on icon ni ni-star-fill"></em></a>
                                                </div>
                                            </div>
                                            <div class="nk-tb-col nk-tb-col-tools">
                                                <ul class="nk-tb-actions gx-1 my-n1">
                                                    <li class="mr-n1">
                                                        <div class="dropdown">
                                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                <ul class="link-list-opt no-bdr">
                                                                    <li><a href="{% url 'shop:delete_shop_category' os.id %}"><em class="icon ni ni-edit"></em><span>Delete Category</span></a></li>
                                                  
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div><!-- .nk-tb-item -->
                                        {% endfor %}

                                        {% endif %}
                                    </div><!-- .nk-tb-list -->
                                   
                                </div><!-- .nk-block -->
                                <div class="nk-add-product toggle-slide toggle-slide-right" data-content="addProduct" data-toggle-screen="any" data-toggle-overlay="true" data-toggle-body="true" data-simplebar>
                                    <div class="nk-block-head">
                                        <div class="nk-block-head-content">
                                            <h5 class="nk-block-title">Add New Category </h5>
                                            <div class="nk-block-des">
                                                <p>Add information about new category.</p>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <form action="#" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                    
                                    <div class="nk-block">
                                        <div class="row g-3">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="platform_name">Platform Name</label>
                                                    <div class="form-control-wrap">
                                                        <input name="platform_name" type="text" class="form-control" id="platform_name" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="platform_slug"> Slug </label>
                                                    <div class="form-control-wrap">
                                                        <input name="platform_slug" type="text" class="form-control" id="platform_slug" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label class="form-label" for="iconImagePath"> Icon Image Path </label>
                                                    <div class="form-control-wrap">
                                                        <div class="custom-file">
                                                            <input name="iconImagePath" type="file" class="custom-file-input" id="iconImagePath" required> 
                                                            <label class="custom-file-label" for="iconImagePath">Choose file</label> 
                                                        </div>
                                                    </div>
                                                </div>
                                            
                                            </div>
                                          
                                        
                                            
                                           
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary"><em class="icon ni ni-plus"></em><span>Add New</span></button>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block -->
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content @e -->




{% endblock content %}

shop/templates/shop/shop_orders.html
{% extends 'rentals/base.html' %}
{% load tagger %}

{% block content %}



  <!-- content @s -->
  <div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block-head nk-block-head-sm">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h3 class="nk-block-title page-title">Shop Orders</h3>
                        </div><!-- .nk-block-head-content -->
                        <div class="nk-block-head-content">
                            <div class="toggle-wrap nk-block-tools-toggle">
                                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em class="icon ni ni-more-v"></em></a>
                                <div class="toggle-expand-content" data-content="pageMenu">
                                    <ul class="nk-block-tools g-3">
                                        <li>
                                            <div class="form-control-wrap">
                                                <div class="form-icon form-icon-right">
                                                    <em class="icon ni ni-search"></em>
                                                </div>
                                                <input type="text" class="form-control" id="default-04" placeholder="Quick search by id">
                                            </div>
                                        </li>
                                    
                                
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .nk-block-head-content -->
                    </div><!-- .nk-block-between -->
                </div><!-- .nk-block-head -->
                <div class="nk-block">
                    <div class="nk-tb-list is-separate is-medium mb-3">
                        <div class="nk-tb-item nk-tb-head">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="oid">
                                    <label class="custom-control-label" for="oid"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col"><span>Order Number</span></div>
                            <div class="nk-tb-col tb-col-md"><span>Date</span></div>
                            <div class="nk-tb-col"><span class="d-none d-mb-block">Status</span></div>
                            <div class="nk-tb-col tb-col-sm"><span>Customer</span></div>
                          
                            <div class="nk-tb-col"><span>Total</span></div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1 my-n1">
                                    <li>
                                        <div class="drodown">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger mr-n1" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                
                                                    <li><a href="#"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                          
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-tb-item -->


                        {% if orders %}
                        {% for val in orders %}
                        <div class="nk-tb-item">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="oid01">
                                    <label class="custom-control-label" for="oid01"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col">
                                <span class="tb-lead"><a href="#">#{{val.ref_code}}</a></span>
                            </div>
                            <div class="nk-tb-col tb-col-md">
                                <span class="tb-sub">{{val.ordered_date}}</span>
                            </div>
                            <div class="nk-tb-col">
                                {% if val.received == False %}
                                <span class="dot bg-warning d-mb-none"></span>
                                <span class="badge badge-sm badge-dot has-bg badge-warning d-none d-mb-inline-flex">In Transit</span>
                                {% elif val.received == True %}
                                <span class="dot bg-success d-mb-none"></span>
                                <span class="badge badge-sm badge-dot has-bg badge-success d-none d-mb-inline-flex">Delivered</span>
                                {% endif %}
                            </div>
                            <div class="nk-tb-col tb-col-sm">
                                <span class="tb-sub">{{val.user.first_name}} {{val.user.last_name}} </span>
                            </div>
                            
                            <div class="nk-tb-col">
                                <span class="tb-lead">₦ {{val.order_total}}</span>
                            </div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1">
                                    <li class="nk-tb-action-hidden"><a href="{% url 'shop:mark_order_as_delivered' val.id %}" class="btn btn-icon btn-trigger btn-tooltip" title="Mark as Delivered" >
                                            <em class="icon ni ni-truck"></em></a></li>
                                    <li class="nk-tb-action-hidden"><a href="{% url 'shop:shop_order_details' val.id %}" class="btn btn-icon btn-trigger btn-tooltip" title="View Order" >
                                            <em class="icon ni ni-eye"></em></a></li>
                                    <li>
                                        <div class="drodown mr-n1">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                    <li><a href="{% url 'shop:shop_order_details' val.id %}"><em class="icon ni ni-eye"></em><span>Order Details</span></a></li>
                                                    <li><a href="{% url 'shop:mark_order_as_delivered' val.id %}"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                 
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}







                    </div><!-- .nk-tb-list -->
                    
                </div><!-- .nk-block -->
            </div>
        </div>
    </div>
</div>
<!-- content @e -->

{% endblock content %}